### ISSUE TITLE
Safety Validator should be updated to accept values on newer cards.

### ISSUE THREAD

**Issue by NerysRhys** [cfogrady/DIM-Modifier#12]
Hi, I've been making changes about requirements for the mons on all the DIMs I haven't completed yet (I want to complete them all before the Vital Lab is taken down), and I've noticed that Agnimon and Wolfmon won't let me save the changes I've made.

I thought it might be because of my backup, so I made another one, but it didn't solve the issue. Do you know the reason why it won't work? Previous versions of your program don't seem to work either.

**Comment by cfogrady** [comment]
There should be some text in the terminal indicating why. I believe some newer DIMs used tables that were bigger than I thought the table could go, which is probably the issue for you as well... You could try turning off "Only Safe Values" and it should let you save.

**Comment by cfogrady** [comment]
> EDIT: Guilmon also won't save unless the box is unchecked because the DIM "has too many evolutions".

Yeah... This is the one that somebody else had brought to my attention. I'll try to update the Safety Validator for both of these.

**Comment by cfogrady** [comment]
Safety validator was reworked for 2.0, but this is basically done.
