### ISSUE TITLE
Jogress evo time not saving

### ISSUE THREAD

**Issue by Desbrina** [cfogrady/DIM-Modifier#27]
I'm trying to modify the shadow howl (trial version) DIM.

I've noticed that the evolution time for the jogress isn't being saved. When i initially load the dim, the time is set correctly in the UI.
I can edit it fine and save. But when reopening the edited file and trying to resave, it tells me character 5 (the metal garurumon) has an evolution but no time set

When i try and save, i do get the below message in the console.

I can set the time again but get the same issue the next time i open the edited dim again

[JavaFX Application Thread] INFO com.github.cfogrady.dim.modifier.data.dim.DimCardDataWriter - Number of evolutions on this dim has changed and the new value is less than table size. Using full table dummy rows
[JavaFX Application Thread] INFO com.github.cfogrady.vb.dim.header.HeaderWriter - Text: BANDAINTPD_0_0_0DIGIMON_DIM2020_

<img width="1248" alt="2023-03-03" src="https://user-images.githubusercontent.com/25529891/222716300-0cb5acbb-6afb-439f-90f7-514583f99457.png">

**Comment by Desbrina** [comment]
I wasn't sure about the console message so I thought I'd post it.

Can confirm that the black roar dim does the same

**Comment by Desbrina** [comment]
Do t know if it helps but I've noticed it only happens when there are no normal evolutions added. If I add one then it seems to save

**Comment by cfogrady** [comment]
Fixed in 2.0.2
