### ISSUE TITLE
Splash image too large

### ISSUE THREAD

**Issue by SeppuCrow621** [cfogrady/DIM-Modifier#31]
Hey there, 
In previous versions we were able to add individual splash images to DiMs for each character that were a size of 80x160, however when attempting to do this on the new version for a custom built character I was met with an error stating that image size is too big and specifying the image must be the regular character sprite size (64x56 or 32x24). If I'm not mistaken, this wouldn't fill the whole screen when the splash image is shown. Is this an error, or am I doing something wrong? I realise I could just compile all the sprites/splash image into a sprite sheet instead, but it would be more convenient to be able to add this at full size separately when adding custom designed characters. 
Thanks!

**Comment by cfogrady** [comment]
🤦🏻‍♂️
Yup. This is a bug. Brought about by me trying to be safe with images.
As you already said, work around for this would be to use the import sprite sheet feature.
I'll put in a fix for the 2.1 update in a few weeks.

**Comment by cfogrady** [comment]
Done in the 2.1 branch.
