### ISSUE TITLE
Error when saving be dim

### ISSUE THREAD

**Issue by Rayipp** [cfogrady/DIM-Modifier#37]
When saving other series of be dim, e.g. tokyo revengers/ MHA / demon slayers,cant save
![EDDDCB45-4DA4-4939-A690-85E9B4309889](https://user-images.githubusercontent.com/120867162/226182405-0926901e-a38b-4bf9-abba-2e1b5e655a7c.jpeg)

**Comment by cfogrady** [comment]
This is a known issue. It's fixed in my 2.1 branch (unreleased).
It will be fixed in the next update. You can work around it by exporting and importing the sprite sheets for those characters (NPC enemies)
https://github.com/cfogrady/DIM-Modifier/issues/24
