### ISSUE TITLE
Errors about multiple evolution times

### ISSUE THREAD

**Issue by Desbrina** [cfogrady/DIM-Modifier#47]
Getting this message when loading the DC Comic vital hero cards
[JavaFX Application Thread] ERROR com.github.cfogrady.dim.modifier.data.dim.DimCardDataReader - BEM encountered with different evolution timers from a single digimon. Please log an issue with the BEM on https://github.com/cfogrady/DIM-Modifier/issues

For some characters the evo time box is showing as blank

**Comment by cfogrady** [comment]
Interesting. That's within the possibilities of the format (which is why I have a very specific error to bring it to my attention), but outside the convention that's been used for every previous card. It breaks my UI, so I'll have to put some thought into how to handle it.

**Comment by Desbrina** [comment]
Also to note, its giving the same message on the two new digimon D3 dims

**Comment by cfogrady** [comment]
I just saw :(
I'll try to take a look at those when my cards come in.

**Comment by Desbrina** [comment]
My guess is it's the two jogresses as they also have normal evolutions as well

**Comment by cfogrady** [comment]
It is the two jogress... They have different jogress timers than regular transformation timers...

**Comment by cfogrady** [comment]
Fixed in 2.1 branch.
