### ISSUE TITLE
On the 2.1 Branch  - Modifying the Jujutsu Kaisen BEM name's sprites always gives E22

### ISSUE THREAD

**Issue by nekojosh** [cfogrady/DIM-Modifier#48]
I've been modifying non-digimon BEMs with the 2.1 version that I compiled out of the branch available here. However I've encountered that no matter how I edit the sprite for any of the names in the Jujutsu Kaisen BEM I always get E22 on the VBBE. No idea what is causing it though. So far that's the only non-digimon BEM that has given me that error.

**Comment by nekojosh** [comment]
I thinks this might be related to the problem...

[JavaFX Application Thread] WARN com.github.cfogrady.vb.dim.header.DimHeaderReader - Presumed DIM Ids 275 and 19 do not match! Please make an issue with the DIM card in question on https://github.com/cfogrady/DIM-Modifier/issues so I purchase and analyze the card

**Comment by cfogrady** [comment]
Different issue. The DIM Id is one that's been brought to my attention for some newer BEMs, but isn't really critical for how the app operates.

Are the name sprites you are using smaller than the old name sprites? I'm wondering if you are hitting https://github.com/cfogrady/DIM-Modifier/issues/43 as an edge case. I've got this fixed and tested locally, but I haven't pushed that fix yet because I want to test on hardware and haven't had the time to do so yet.

**Comment by nekojosh** [comment]
I don't think the sprites are the issue. I was playing around with this yesterday and tried just opening my vanilla bin dump with the dim-modifier 2.1 and saving it without making any changes to the sprites or values, then I restore it to the BEM and used it on the VBBE. I got error 22. I then compared with a Hex editor both the vanilla dump and the one that had been unchanged but saved throught dim-modifier 2.1 and noticed that the header had a difference in the 0x35 offset where FF had been changed to FE. I manually changed it back to FF and saved the bin then tried to used on the VBBE and this time it didn't give me error 22, it tried copying all files and but failed when at the third dot(from the loading process on the VBBE) and then gave me error 24.
I currently own all non-digimon BEMs release except for the Run For Money one, so if you want I could share the bins with you and test for you. Just looking to help :)

**Comment by cfogrady** [comment]
That's awesome sleuthing! Thanks. That all makes a ton of sense. I'll put in a change to differentiate between those two values in the program.

I think the problem when you changed it, is that the end of image checksum includes the header values. So you would need to change the header value and then recalculate the end of image checksum. But I should be able to get a fix for that into the 2.1 branch this week.

**Comment by nekojosh** [comment]
Awesome! Let me know if there is anything else I can do to help.

**Comment by cfogrady** [comment]
This is fixed and pushed on the 2.1 branch FYI.

**Comment by nekojosh** [comment]
I have rebuild both the VB-DIM-Reader and the DIM-Modifier and can confirm that it works now. Will test down the road with other non-digimon BEMs but at least the Jujutsu Kaisen one is working perfectly. Thanks for all the work you do for the community.
