### ISSUE TITLE
Dim Failed In Custom Digimon Frontier

### ISSUE THREAD

**Issue by n11ku** [cfogrady/DIM-Modifier#7]
cannot instal my custom dim like inject agnimon, wolfmon sprite group in louwemon dim,but when i tyring inject lord knigtmon sprite from fairymon frontier & dynasmon sprite from chakomon frontier in mad black roar,is working & success instal to my vbv,even all digimon frontier dim bin file can instal to my vbv,only failed when tried edit all digimon frontier status,maybe becuase i delete all fusion recruitment,even i write again fusion list like original but always say dim failed,is bug bro?

**Comment by cfogrady** [comment]
This is a known with the VBV. DIMs after Dynasty of Evil, have a new hash signature to ensure the sprites haven't been tampered with. You should be able to run this DIM on an old VB, or make the modifications to a DIM from before Dynasty of Evil (like mad back roar). There is a work around that I would like to implement at some point, but for now changes to sprites in newer DIMs won't work on the VBV

**Comment by n11ku** [comment]
oh,ok bro

**Comment by cfogrady** [comment]
This feature now works with version 1.5.2
