### ISSUE TITLE
Application fails to run

### ISSUE THREAD

**Issue by KaijuBird** [cfogrady/DIM-Modifier#8]
Wish I could offer an error, but it just refuses to do anything. Tried turning off antivirus and it still won't, I don't even get a warning regarding it. Tried using older versions and none of them work, tried running as admin, no effect.

**Comment by cfogrady** [comment]
Unfortunately, I can't do much without being able to reproduce.
Firstly, try running the exe from a command prompt window. That will hopefully yield some actual error messages that I might be able to help with.

Second, any details you can provide me about your environment may also be helpful... Windows Version? Running inside a VM?

No guarantee those details would help me identify the issue, but it might.

**Comment by KaijuBird** [comment]
Apologies for not replying sooner, but after I sent that last message I continued to try various approaches and for some reason it worked after running the compatibility troubleshooter. 
Had already tried running it in compatibility mode for Windows 8 (along with others) but that hadn't worked, however when it found that option it's self as the 'solution' after running the troubleshooter it worked flawlessly. Saving that preference has continued to allow it to run normally.

I'm using Windows 10, no VM, and no idea why it was doing that.

Sorry for wasting your time, and thank you for creating this application.
