### ISSUE TITLE
Incompatibility issue

### ISSUE THREAD

**Issue by FatalXFury** [cfogrady/DIM-Modifier#9]
Hello. Want to start off by saying i and the rest of the VB community appreciate what youve made for our Dims. My laptop broke recently and i ended up disting off a netbook and wanted to use the Dim Modifier to customize my dims. Unfortunately, it wont open on my netbook. A pop up comes up saying it only runs on 32 and 64 bit. Im running Windows 7 Starter. Is there a way to make it compatible with my OS?
![1667382850454697578620488187843](https://user-images.githubusercontent.com/88270571/199459424-ab39f429-a6af-4572-86dd-e27a1fb01d2b.jpg)

**Comment by cfogrady** [comment]
I don't know, but my initial guess is probably not easily.

I could do some research if you can give me the processor your computer uses... but my gut instinct is that the tools I'm using to compile the binary only work with newer versions of Windows or linux.

**Comment by FatalXFury** [comment]
My Acer Netbook uses an Intel Atom. I really want to use the modifier. Just
cant afford a new laptop or pc right now.

**Comment by FatalXFury** [comment]
I managed to fix a chromebook i had. So this is no longer an issue for me.

**Comment by cfogrady** [comment]
Great. Glad it's working with the other machine!
